# Generated by Django 6.0.4 on 2026-04-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportHeliport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField()),
                ('information_valid_since', models.DateTimeField()),
                ('information_valid_until', models.DateTimeField()),
                ('aixm_sequence_number', models.IntegerField()),
                ('aixm_correction_number', models.IntegerField()),
                ('aixm_designator', models.CharField()),
                ('aixm_name', models.CharField()),
                ('aixm_location_indicator_icao', models.CharField()),
                ('aixm_designator_iata', models.CharField()),
                ('aixm_type', models.CharField()),
                ('aixm_certified_icao', models.BooleanField(null=True)),
                ('aixm_control_type', models.CharField()),
                ('aixm_field_elevation_in_meter', models.FloatField(null=True)),
                ('aixm_field_elevation_accuracy_in_meter', models.FloatField(null=True)),
                ('aixm_magnetic_variation', models.FloatField(null=True)),
                ('aixm_magnetic_variation_accuracy', models.FloatField(null=True)),
                ('aixm_date_magnetic_variation', models.IntegerField(null=True)),
                ('aixm_magnetic_variation_change', models.FloatField(null=True)),
                ('aixm_reference_temperature_in_celcius', models.FloatField(null=True)),
                ('aixm_certification_date', models.DateField(null=True)),
                ('aixm_certification_expiration_date', models.DateField(null=True)),
                ('aixm_served_city', models.CharField()),
                ('aixm_latitude', models.FloatField()),
                ('aixm_longitude', models.FloatField()),
                ('aixm_annotations', models.CharField()),
                ('aixm_availability', models.CharField()),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('uuid', 'aixm_sequence_number', 'aixm_correction_number'), name='app airportheliport 元素唯一')],
            },
        ),
        migrations.CreateModel(
            name='Airspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField()),
                ('information_valid_since', models.DateTimeField()),
                ('information_valid_until', models.DateTimeField()),
                ('aixm_sequence_number', models.IntegerField()),
                ('aixm_correction_number', models.IntegerField()),
                ('aixm_type', models.CharField()),
                ('aixm_designator', models.CharField()),
                ('aixm_name', models.CharField()),
                ('aixm_geometry_components', models.JSONField()),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('uuid', 'aixm_sequence_number', 'aixm_correction_number'), name='app airspace 元素唯一')],
            },
        ),
    ]
