# Generated by Django 6.0.4 on 2026-04-21 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElevatedPoint',
            fields=[
                ('point_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.point')),
                ('aixm_elevation', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
                ('aixm_special_elevation', models.CharField()),
            ],
            bases=('app.point',),
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField()),
                ('information_valid_since', models.DateTimeField()),
                ('information_valid_until', models.DateTimeField()),
                ('aixm_sequence_number', models.IntegerField()),
                ('aixm_correction_number', models.IntegerField()),
                ('aixm_designator', models.CharField()),
                ('aixm_nominal_length', models.FloatField(null=True)),
                ('aixm_length_accuracy', models.FloatField(null=True)),
                ('aixm_nominal_width', models.FloatField(null=True)),
                ('aixm_width_accuracy', models.FloatField(null=True)),
                ('aixm_width_shoulder', models.FloatField(null=True)),
                ('aixm_annotations', models.CharField()),
                ('aixm_associated_airport_heliport', models.CharField()),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('uuid', 'aixm_sequence_number', 'aixm_correction_number'), name='app runway 元素唯一')],
            },
        ),
        migrations.CreateModel(
            name='RunwayDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField()),
                ('information_valid_since', models.DateTimeField()),
                ('information_valid_until', models.DateTimeField()),
                ('aixm_sequence_number', models.IntegerField()),
                ('aixm_correction_number', models.IntegerField()),
                ('aixm_designator', models.CharField()),
                ('aixm_true_bearing', models.FloatField(null=True)),
                ('aixm_true_bearing_accuracy', models.FloatField(null=True)),
                ('aixm_used_runway', models.CharField()),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('uuid', 'aixm_sequence_number', 'aixm_correction_number'), name='app runwaydirection 元素唯一')],
            },
        ),
        migrations.CreateModel(
            name='RunwayCentrelinePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField()),
                ('information_valid_since', models.DateTimeField()),
                ('information_valid_until', models.DateTimeField()),
                ('aixm_sequence_number', models.IntegerField()),
                ('aixm_correction_number', models.IntegerField()),
                ('aixm_role', models.CharField()),
                ('aixm_on_runway', models.CharField()),
                ('aixm_annotations', models.JSONField()),
                ('aixm_associated_declared_distances', models.JSONField()),
                ('aixm_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.elevatedpoint')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('uuid', 'aixm_sequence_number', 'aixm_correction_number'), name='app runwaycentrelinepoint 元素唯一')],
            },
        ),
        migrations.CreateModel(
            name='AirportHeliport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField()),
                ('information_valid_since', models.DateTimeField()),
                ('information_valid_until', models.DateTimeField()),
                ('aixm_sequence_number', models.IntegerField()),
                ('aixm_correction_number', models.IntegerField()),
                ('aixm_designator', models.CharField()),
                ('aixm_name', models.CharField()),
                ('aixm_location_indicator_icao', models.CharField()),
                ('aixm_designator_iata', models.CharField()),
                ('aixm_type', models.CharField()),
                ('aixm_certified_icao', models.BooleanField(null=True)),
                ('aixm_control_type', models.CharField()),
                ('aixm_field_elevation', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('aixm_magnetic_variation', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('aixm_date_magnetic_variation', models.DecimalField(decimal_places=0, max_digits=4, null=True)),
                ('aixm_reference_temperature', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('aixm_certification_date', models.DateField(null=True)),
                ('aixm_certification_expiration_date', models.DateField(null=True)),
                ('aixm_served_city', models.CharField()),
                ('aixm_annotations', models.JSONField()),
                ('aixm_availability', models.JSONField()),
                ('aixm_arp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.elevatedpoint')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('uuid', 'aixm_sequence_number', 'aixm_correction_number'), name='app airportheliport 元素唯一')],
            },
        ),
    ]
