# Generated by Django 6.0.4 on 2026-04-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportHeliport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField()),
                ('information_valid_since', models.DateTimeField()),
                ('information_valid_until', models.DateTimeField()),
                ('aixm_sequence_number', models.IntegerField()),
                ('aixm_correction_number', models.IntegerField()),
                ('aixm_designator', models.CharField()),
                ('aixm_name', models.CharField()),
                ('aixm_location_indicator_icao', models.CharField()),
                ('aixm_designator_iata', models.CharField()),
                ('aixm_type', models.CharField()),
                ('aixm_certified_icao', models.BooleanField(null=True)),
                ('aixm_control_type', models.CharField()),
                ('aixm_field_elevation', models.FloatField(null=True)),
                ('aixm_field_elevation_accuracy', models.FloatField(null=True)),
                ('aixm_magnetic_variation', models.FloatField(null=True)),
                ('aixm_magnetic_variation_accuracy', models.FloatField(null=True)),
                ('aixm_date_magnetic_variation', models.IntegerField(null=True)),
                ('aixm_magnetic_variation_change', models.FloatField(null=True)),
                ('aixm_reference_temperature', models.FloatField(null=True)),
                ('aixm_certification_date', models.DateField(null=True)),
                ('aixm_certification_expiration_date', models.DateField(null=True)),
                ('aixm_city', models.CharField()),
                ('aixm_latitude', models.FloatField()),
                ('aixm_longitude', models.FloatField()),
            ],
        ),
    ]
