# Generated by Django 6.0.4 on 2026-04-21 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airportheliport',
            old_name='aixm_annotations',
            new_name='aixm_annotation',
        ),
        migrations.RenameField(
            model_name='runway',
            old_name='aixm_annotations',
            new_name='aixm_annotation',
        ),
        migrations.RenameField(
            model_name='runwaycentrelinepoint',
            old_name='aixm_annotations',
            new_name='aixm_annotation',
        ),
    ]
