# Generated by Django 6.0.4 on 2026-04-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunwayDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField()),
                ("information_valid_since", models.DateTimeField()),
                ("information_valid_until", models.DateTimeField()),
                ("aixm_sequence_number", models.IntegerField()),
                ("aixm_correction_number", models.IntegerField()),
                ("aixm_designator", models.CharField()),
                ("aixm_true_bearing", models.FloatField(null=True)),
                ("aixm_true_bearing_accuracy", models.FloatField(null=True)),
                ("aixm_used_runway", models.CharField()),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "uuid",
                            "aixm_sequence_number",
                            "aixm_correction_number",
                        ),
                        name="app runwaydirection 元素唯一",
                    )
                ],
            },
        ),
    ]
