# Generated by Django 6.0.4 on 2026-04-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_aixm_annotations_airportheliport_aixm_annotation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runway',
            name='aixm_length_accuracy',
        ),
        migrations.RemoveField(
            model_name='runway',
            name='aixm_width_accuracy',
        ),
        migrations.AlterField(
            model_name='runway',
            name='aixm_annotation',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='runway',
            name='aixm_nominal_length',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='runway',
            name='aixm_nominal_width',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='runway',
            name='aixm_width_shoulder',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
