# Generated by Django 6.0.4 on 2026-04-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_runwaycentrelinepoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="runwaycentrelinepoint",
            name="aixm_on_runway",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
    ]
