# Generated by Django 6.0.4 on 2026-04-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_runway_aixm_length_accuracy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runwaydirection',
            name='aixm_true_bearing_accuracy',
        ),
        migrations.AlterField(
            model_name='runwaydirection',
            name='aixm_true_bearing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
