# Generated by Django 6.0.4 on 2026-04-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_runwaycentrelinepoint_aixm_on_runway"),
    ]

    operations = [
        migrations.AddField(
            model_name="runwaycentrelinepoint",
            name="aixm_associated_declared_distance",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
