# Generated by Django 6.0.4 on 2026-04-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_runwaycentrelinepoint_aixm_associated_declared_distance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="runwaycentrelinepoint",
            name="aixm_associated_declared_distance",
        ),
        migrations.RemoveField(
            model_name="runwaycentrelinepoint",
            name="aixm_role",
        ),
        migrations.AddField(
            model_name="runwaycentrelinepoint",
            name="content",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
