# Generated by Django 6.0.4 on 2026-04-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app",
            "0006_remove_runwaycentrelinepoint_aixm_associated_declared_distance_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="runwaycentrelinepoint",
            name="aixm_role",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
    ]
