# Generated by Django 6.0.4 on 2026-04-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_runwaycentrelinepoint_aixm_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="runwaycentrelinepoint",
            name="aixm_annotations",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
