# Generated by Django 6.0.4 on 2026-04-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_runwaycentrelinepoint_aixm_annotations"),
    ]

    operations = [
        migrations.AddField(
            model_name="runwaycentrelinepoint",
            name="aixm_associated_declared_distances",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
